### PR TITLE
Do not set awaiting-changes label on merged PRs

### LINKED ISSUE #126: Do not detect mergeability if the PR is already merged
It sets an `awaiting-changes` label for nothing.

### PR DESCRIPTION
**Pull request by Srynetix**
Closes #126

### CODE REVIEW

**Comment by Srynetix** [comment]
bot automerge+

**Comment by Srynetix** [comment]
> bot automerge+

Automerge enabled by **Srynetix**

_Beep boop, i'm a bot!_ :robot:

**Comment by Srynetix** [comment]
bot qa+

**Comment by Srynetix** [comment]
> bot qa+

QA is marked as pass by **Srynetix**.

_Beep boop, i'm a bot!_ :robot:

**Review by lucasmart — APPROVED** [review]

**Comment by Srynetix** [comment]
Pull request successfully auto-merged! (strategy: 'squash')

_Beep boop, i'm a bot!_ :robot:

**Pull request merged**
