### PR TITLE
Add Redis lock on reviews

### LINKED ISSUE #103: Could not run SQL query: duplicate key value violates unique constraint "review_pull_request_id_username_key"
It seems there is a problem / race condition when registering reviews sometimes.

```
postgres_1  | 2021-09-29 15:51:27.778 UTC [121387] STATEMENT:  INSERT INTO "review" ("pull_request_id", "username", "state", "required", "valid") VALUES ($1, $2, $3, $4, $5) RETURNING "review"."id", "review"."pull_request_id", "review"."username", "review"."state", "review"."required", "review"."valid"
postgres_1  | 2021-09-29 15:51:29.000 UTC [121387] ERROR:  duplicate key value violates unique constraint "review_pull_request_id_username_key"
postgres_1  | 2021-09-29 15:51:29.000 UTC [121387] DETAIL:  Key (pull_request_id, username)=(326, ripoul) already exists.
postgres_1  | 2021-09-29 15:51:29.000 UTC [121387] STATEMENT:  INSERT INTO "review" ("pull_request_id", "username", "state", "required", "valid") VALUES ($1, $2, $3, $4, $5) RETURNING "review"."id", "review"."pull_request_id", "review"."username", "review"."state", "review"."required", "review"."valid"
postgres_1  | 2021-09-29 15:51:29.000 UTC [121384] ERROR:  duplicate key value violates unique constraint "review_pull_request_id_username_key"
postgres_1  | 2021-09-29 15:51:29.000 UTC [121384] DETAIL:  Key (pull_request_id, username)=(326, ripoul) already exists.
postgres_1  | 2021-09-29 15:51:29.000 UTC [121384] STATEMENT:  INSERT INTO "review" ("pull_request_id", "username", "state", "required", "valid") VALUES ($1, $2, $3, $4, $5) RETURNING "review"."id", "review"."pull_request_id", "review"."username", "review"."state", "review"."required", "review"."valid"
```

### PR DESCRIPTION
**Pull request by Srynetix**
### Fixed

- Remove data races on reviews using a Redis lock

bot noqa+
bot admin-set-needed-reviewers 2

Closes #103

### CODE REVIEW

**Comment by Srynetix** [comment]
_This is an auto-generated message summarizing this pull request._

:pencil: &mdash; **Rules**

> - :speech_balloon: **Title validation**: _valid!_ :heavy_check_mark:
>   - _Rule:_ None
> - :twisted_rightwards_arrows: **Merge strategy**: _squash_


:speech_balloon: &mdash; **Status comment**

> - :construction: **WIP?** No :heavy_check_mark:
> - :checkered_flag: **Checks**: _running..._ :clock2:
> - :mag: **Code reviews**: _passed! (0 given / 0 required)_ :heavy_check_mark:
> - :test_tube: **QA**: _skipped._ :heavy_check_mark:
> - :lock: **Locked?**: No :heavy_check_mark:

:gear: &mdash; **Configuration**

> - :twisted_rightwards_arrows: **Automerge**: :x:

:scroll: &mdash; **Current status**

> _Pending: Waiting for checks_

[_See checks output by clicking this link :triangular_flag_on_post:_](https://github.com/sharingcloud/github-scbot/pull/104/checks)

_Beep boop, i'm a bot!_ :robot:

**Comment by Srynetix** [comment]
> bot noqa+

QA is marked as skipped by **Srynetix**.

---

> bot admin-set-needed-reviewers 2

Needed reviewers count set to **2** for this PR.

_Beep boop, i'm a bot!_ :robot:

**Comment by Srynetix** [comment]
bot automerge+

**Comment by Srynetix** [comment]
> bot automerge+

Automerge enabled by **Srynetix**

_Beep boop, i'm a bot!_ :robot:

**Review by FloZone — APPROVED** [review]

**Comment by Srynetix** [comment]
Bon on va dire que c'est bon et on va sortir une 0.13.1

**Comment by Srynetix** [comment]
bot automerge-

**Comment by Srynetix** [comment]
bot automerge+

**Comment by Srynetix** [comment]
> bot automerge+

Automerge enabled by **Srynetix**

_Beep boop, i'm a bot!_ :robot:

**Comment by Srynetix** [comment]
bot admin-set-needed-reviewers 1

**Comment by Srynetix** [comment]
> bot admin-set-needed-reviewers 1

Needed reviewers count set to **1** for this PR.

_Beep boop, i'm a bot!_ :robot:

**Review by FloZone — APPROVED** [review]

**Comment by Srynetix** [comment]
Pull request successfully auto-merged! (strategy: 'squash')

_Beep boop, i'm a bot!_ :robot:

**Pull request merged**
