### PR TITLE
Handle conflicts

### LINKED ISSUE #123: Handle conflicts
If there are conflicts on a pull request, the bot should set the "awaiting-changes" label. (or a specific conflict label?)

### PR DESCRIPTION
**Pull request by Srynetix**
Closes #123

### CODE REVIEW

**Comment by Srynetix** [comment]
_This is an auto-generated message summarizing this pull request._

:pencil: &mdash; **Rules**

> - :speech_balloon: **Title validation**: _valid!_ :heavy_check_mark:
>   - _Rule:_ None
> - :twisted_rightwards_arrows: **Merge strategy**: _squash_


:speech_balloon: &mdash; **Status comment**

> - :construction: **WIP?** No :heavy_check_mark:
> - :checkered_flag: **Checks**: _running..._ :clock2:
> - :mag: **Code reviews**: _waiting..._ (0 given / 1 required) :clock2:
> - :test_tube: **QA**: _waiting..._ :clock2:
> - :lock: **Locked?**: No :heavy_check_mark:
> - :twisted_rightwards_arrows: **Mergeable?**: Yes :heavy_check_mark:

:gear: &mdash; **Configuration**

> - :twisted_rightwards_arrows: **Automerge**: :x:

:scroll: &mdash; **Current status**

> _Pending: Waiting for checks_

[_See checks output by clicking this link :triangular_flag_on_post:_](https://github.com/sharingcloud/github-scbot/pull/125/checks)

_Beep boop, i'm a bot!_ :robot:

**Review by FloZone — APPROVED** [review]

**Comment by Srynetix** [comment]
bot qa+

**Comment by Srynetix** [comment]
> bot qa+

QA is marked as pass by **Srynetix**.

_Beep boop, i'm a bot!_ :robot:

**Comment by Srynetix** [comment]
bot merge

**Comment by Srynetix** [comment]
> bot merge

Pull request successfully merged by Srynetix! (strategy: 'squash')

_Beep boop, i'm a bot!_ :robot:

**Pull request merged**
